GET https://api.mapbox.com/optimized-trips/v2/ca408fe6-f335-4190-ab3b-814673ba8830?access_token=pk.eyJ1IjoiYWRyaWFuYXJpcyIsImEiOiJja3kzOTl0YzkwdGZuMm5xdHJzMHJ5b2p4In0.kXH2cOyOUq6WIOmYH5sKAA
Host: api.mapbox.com
Content-Type: application/json